FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    e2fsprogs \
    qemu-user-static \
    python3 \
    bsdutils \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /mnt/sdcard /workspace

WORKDIR /workspace
