[package]
name = "os"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
buddy_system_allocator = "0.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = "0.4"
xmas-elf = "0.7.0"
spin = "0.7.0"
virtio-drivers = { path = "../vendor/virtio-drivers-old" }
smoltcp = { path = "../vendor/smoltcp", default-features = false, features = [
    "alloc", "log",
    "medium-ethernet", "medium-ip",
    "proto-ipv4",
    "socket-tcp", "socket-udp", "socket-icmp", "socket-raw",
] }
easy-fs = { path = "../easy-fs" }
lwext4_rust = { path = "../vendor/lwext4_rust", default-features = false, optional = true }
fatfs = { path = "../vendor/rust-fatfs", default-features = false, features = ["alloc", "lfn", "unicode"] }
volatile = { path = "../vendor/volatile-0.3.0" }

[patch.crates-io]
volatile = { path = "../vendor/volatile-0.3.0" }
[features]
ext4 = ["lwext4_rust"]
legacy_qemu = []

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { path = "../vendor/riscv", features = ["inline-asm"] }
