[build]
target = "riscv64gc-unknown-none-elf"
target-dir = "target-user"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-args=-Tsrc/linker.ld",
]

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-args=-Tsrc/linker-loongarch64.ld",
]
